services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: image-quality-backend

    expose:
      - "8000"

    volumes:
      - ./backend/uploads:/app/backend/uploads

    restart: unless-stopped


  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile

    container_name: image-quality-frontend

    ports:
      - "3000:80"

    depends_on:
      - backend

    restart: unless-stopped